version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"

services:
  mev-boost:
    restart: "${RESTART}"
    build:
      context: ./flashbots
      dockerfile: ${MEV_DOCKERFILE}
      args:
        - BUILD_TARGET=${MEV_SRC_BUILD_TARGET}
        - DOCKER_TAG=${MEV_DOCKER_TAG}
    image: mev-boost:local-merge
    entrypoint:
      - /app/mev-boost
      - -addr
      - 0.0.0.0:18550
      - -relays
      - ${MEV_RELAYS}
      - -${NETWORK}
    <<: *logging
  eth:
    depends_on:
      - mev-boost
